### ISSUE TITLE
Serialization Problem

### ISSUE THREAD

**Issue by allenwyma** [timroes/aXMLRPC#26]
I'm trying to use your library to connect to OpenERP through XML-RPC, but I'm having the hardest time. I've been trying arrays and ArrayLists, but to no avail.

In order to search for information, you have to send over a 2 dimmensional array of search information such as [['name','=','apple'],['shape','=','round']], but every time I ALWAYS get a "No serializer found" exception. This needs to go at the end, like so:

``` java
public void search(ArrayList<ArrayList<String>>... values)
    {
        client.callAsync(this, "execute", credentials.getDatabase(), credentials.getUid(), 
                credentials.getPassword(), table, "search", values);
    }
```

I've already implemented the same application with iOS, and used Python to connect in this manner, so it has to be something in the XML-RPC specification that should let you do thing. Above, as you can see, I saw you can use an ArrayList, but I dont' mind using a 2 dimensional original array.

Any solutions on how to solve this? Thanks.

Sorry about opening, again. I forgot I was in the wrong account.

**Comment by skeppi** [comment]
@HangingClowns  hey could you pls elaborate more and share your code if possible i'm tryin to perform a search and display in a onclick list items 
I would very much appreciate it thanxxx

**Comment by HangingClowns** [comment]
What do you want to know?

**Comment by skeppi** [comment]
I want to fetch Strings from database and pass them so they are visible on the list of items. for example i want to search the res.partner and return the names of partner given some conditions

**Comment by skeppi** [comment]
this is my code: i'm getting : No serializer found for type java.lang.object what i dont understand is that is the reply from the server will have the result of the search? so if it's a lot of parameters means that i'm passing them as one string? ppls HELP 
Object[] l = { "is_company", "=", false };
        Object[] filter = { l };
        SearchIdTask = odoo.Search_read(listner,"db","1","password","res.partner",filter);

this is how the search_read is defined 
public Long Search_read (XMLRPCCallback Listner, String db, String uid, String password, String object, Object[] conditions){
        Long id = client.callAsync(Listner,"execute_kw", db,Integer.parseInt(uid),password,object,"Search_read",conditions);
        return id;
    }

and here is the listener
XMLRPCCallback listner = new XMLRPCCallback() {
        @Override
        public void onResponse(long id, Object result) {
            Looper.prepare();
            if(id == SearchIdTask){
                if (result instanceof Boolean && (Boolean) result == false)
                {
                    odoo.MessageDialog(Second.this,"SEARCH ERROR, Please Try Again");

                }else{
                    String res = result.toString();
                    odoo.MessageDialog(Second.this, "" + res);
                }

            }
            Looper.loop();
        }

**Comment by skeppi** [comment]
actually i'm not getting a response from the server but an error either from XMLRPCexception or XMLRPCserverexception

**Comment by skeppi** [comment]
Hello I'm so sorry but i managed to fix that but now i have a problem when i execute this:
Map<String, List> emptyMap = new HashMap<>();
        List<String> filter = Arrays.asList("is_company", "=", "false");
        odoo = new OdooUtility("http://10.10.35.7:8069", "object");
        SearchIdTask = odoo.search_read(listner, "dbodoo", "1", "Jorg53089", "res.partner", filter, emptyMap);

which results in an XMLRPCServerException
i get this error: 
AttributeError: 'str' object has no attribute 'insert'
any thoughts about what I'm doing wrong?

**Comment by gturri** [comment]
@skeppi It looks like the server replied with an error and that's what aXMLRPC is reporting

You might want to use the latest commit of aXMLRPC I just pushed (https://github.com/gturri/aXMLRPC/commit/500fe0ebb80a5ecad1c521ce4c35eed2fcdee5a3) and instantiate the XMLRPCClient with the new FLAGS_DEBUG, in order to confirm this.

**Comment by skeppi** [comment]
how do i do that exactly? sorry I'm very new to this should i download the library you provided? or what also i dont understand why it giving me that error !

**Comment by skeppi** [comment]
@gturri

**Comment by gturri** [comment]
@skeppi  You should:

1. use the latest sources of aXMLRPC
2. then add the debug flag in your code

The exact steps to use the latest sources, depends on how you're using this library (Are you using Maven or Gradle? Did you download a jar? Have you copied the sources?).
If you provide me with more details, I could be more specific if you need help for this part.

Once you're using the latest version, look for the place where you're doing "new XMLRPCClient(...)"  and add the debug flag.
More precisely: as far as I understand, you're doing 

    client = new XMLRPCClient(url);

just turn this line into

    client = new XMLRPCClient(url, XMLRPCClient.FLAGS_DEBUG);

Once all of this is done, run your application on a laptop, and it will print more info on the console.

**Comment by skeppi** [comment]
@gturri I downloaded the jar thank you so much so i will be able to know what is causing the error?

**Comment by gturri** [comment]
You may go to https://turri.fr/temp_github/ in order to download both `aXMLRPC-1.8.4-SNAPSHOT.jar`	(the latest version with the debug flag), and `jISO8601-0.2.jar` (which is a dependency of aXMLRPC)

Once you have those files, you may add them to your project as you did in the first place.

**Comment by skeppi** [comment]
@gturri Thank you so much can i bother later if i have another error it's just because it's a school project and i'm on a deadline thank you so muchhh!!!

**Comment by skeppi** [comment]
@gturri I got this: + the usual error after that of course

I/System.out: <?xml version="1.0" encoding="UTF-8"?><methodResponse>
I/System.out: <fault>
I/System.out: <value>
I/System.out:             <struct>
I/System.out: <member>
I/System.out: <name>faultCode</name>
I/System.out: <value>
I/System.out:                         <int>1</int>
W/art: Suspending all threads took: 617.319ms
 I/System.out:                     </value>
 I/System.out: </member>
 I/System.out: <member>
 I/System.out: <name>faultString</name>
 I/System.out: <value>

**Comment by skeppi** [comment]
@gturri Sorry something went wrong and the tags disappeard:
I/System.out: <?xml version="1.0" encoding="UTF-8"?>
I/System.out:fault 
I/System.out: value
I/System.out: struct
I/System.out: member
I/System.out: name faultCode name/
I/System.out: value
I/System.out: int 1 int/
W/art: Suspending all threads took: 617.319ms
I/System.out: value/
I/System.out: member/
I/System.out: member
I/System.out: string faultString string/
I/System.out:value
then the error above

**Comment by gturri** [comment]
(tips: when you post code in a github review, start the line with 4 whitespaces in order to display it correctly (it also works like this on several other platforms, for instance Stackoverflow). Not that I edited most of your previous message, that's why it works)

> can i bother later if i have another error 

Well, I maintain this project -among others- as a hobby on my spare time. So you may ask for more help, but I do not guarantee that I'll be able to reply quickly (or that I'll be able to reply at all).
If you need to save time, perhaps you'll want to spend more time investigating issues yourself (reading doc, using a debugger, ...). Actually I'm pretty sure it would save you time in the long run.

That being said, regarding the error your experiencing: it's the server which is replying with an error, so there's not much aXMLRPC can do. My intuition is that you may be querying the server with either an invalid method name, or incorrect parameters. That's why I added the debug flag, because it would have let you see the content of the query actually made, and the consequent reply. Then it would have probably been easy for you to look at your server documentation.

However, there are two things that I find surprising:

* In the output you posted above, we only see the reply from the server, not the query. Did you truncate the output, or is it actually missing? (the query should start with `<methodCall>`)
* I would have expected to find the error message you posted previously (`AttributeError: 'str' object has no attribute 'insert'`) in the server reply.

Now, what should be done yet?
Try identifying a query which leads to a reply in error (ie: with a `<fault>` tag). Once have both the query and the reply, there are some options:

* if the query doesn't match what you expected then look at your code. If you're pretty sure your code shouldn't lead to this query, then perhaps there's a bug in aXMLRPC. If it's the case, the best thing to do would be to extract a minimal snippet of code that would reproduce the bug (see sscce.org)
* on the other hand, if you don't understand why this query leads to this error, then you might want to look at odoo's documentation, to ensure the query should yield a different result. And if it appears you followed correctly their doc, then you might want to open a bug report to the Odoo's guys

**Comment by skeppi** [comment]
@gturri thank you so much for you time
After long investigation, i rewrote the method and found that i have a problem with the filter which is the parameters i'm passing (the conditions to perform the search)

Thank you
