### ISSUE TITLE
introduce a new DateTimeSerializer

### ISSUE THREAD

**Issue by flohmueller** [timroes/aXMLRPC#42]
Hi Tim,

According to the [XMLRPC Spec](http://xmlrpc.scripting.com/spec.html) the dateTime values should conform to [ISO 8601](http://en.wikipedia.org/wiki/ISO_8601).

Maybe you could create a less strict `DateTimeSerializer`..!?
The accepted answer from this [stackoverflow question](http://stackoverflow.com/questions/2201925/converting-iso-8601-compliant-string-to-java-util-date) hints that you could simply use the data type converter in JAXB (for iso-8601 compliant datetimes: `javax.xml.bind.DatatypeConverter.parseDateTime`)

What do you think?

**Comment by gturri** [comment]
Hi,

I'm using aXMLRPC to communicate with instances of Dokuwiki.
With https://github.com/splitbrain/dokuwiki/commit/4d1366e45cecd27c337b0a8d606cfcde58f9ac8c; Dokuwiki changed the way dates are encoded. 

Before this commit it, it returned eg:

    <dateTime.iso8601>20141110T23:38:51</dateTime.iso8601>

Now it returns eg:

    <dateTime.iso8601>2014-11-10T23:38:51+0000</dateTime.iso8601>

and it seems aXMLRPC is unable to parse it.

As far as I understand, the fix @flohmueller is talking about, would fix it. @timroes, what do you think? Would you accept a PR doing something like this?

**Comment by timroes** [comment]
Hi @gturri,

since you made so much already, I added you as a collaborator to the project so you can directly push to this repository (and should be able to merge any PR or similar).
I haven't had added this feature anymore, because I started working on a version 2 (found in branch develop-v2) which is a complete rewrite and should be way better designed than the old library (e.g. having modular serializers, deserializers, so that errors like in this issue, could be solved by plugins ad hoc before a real fix is there). Unfortunately I haven't had spend much time anymore in this project, due to other (more interesting :D) projects. But please feel free to add this feature to v1 or do with v2 whatever you like. Please also feel free to add yourself to the LICENSE file as an author.

Cheers,
Tim

**Comment by gturri** [comment]
Thank you for giving me those permissions.

I made a fix (Dokuwiki compatible), but since it's rather ugly, I'd like to let you a chance to look at it.

Moreover, I need you anyway since it would be nice to push a 1.8.1 maven package :)
