### ISSUE TITLE
DateTimeSerializer uses javax.xml.bind...

### ISSUE THREAD

**Issue by HectorFGarcia** [timroes/aXMLRPC#47]
...and that package doesn't exists on Android, so you can't run the class properly.

**Comment by timroes** [comment]
You can use the 1.8.0 version, until this issue is fixed.

/cc @gturri This is true, and that part of the code would need changes again to properly work on Android.

**Comment by gturri** [comment]
@HectorFGarcia can you share pointers that would show how we can parse ISO 8601 dates on Android?

**Comment by HectorFGarcia** [comment]
No, sorry, I never did it before so I don't have a single clue. Until now I always used the Apache's XMLRPC library.

Maybe in android.util.* could be something to help, idk.

**Comment by timroes** [comment]
We should not use android.* to maintain support for both regular java and android. `SimpleDateFormat` should work. Till end of month I am not really able to code in a reasonable manner, so I can't really look into it till then.

**Comment by gturri** [comment]
I tried a POC on my fork (branch "dates": https://github.com/gturri/aXMLRPC/tree/dates) which

* doesn't use javax.xml.bind
* is still able to parse more types of ISO-8601 dates than before (including dates serialized with a timezone)

It still needs more tests and some refactoring, but meanwhile, since I'm not familiar with Android development, @HectorFGarcia could you take a moment to tell me if it solves you're issue?

Note: as explained in #49, I had to change the groupId in this fork, which is now fr.turri

**Comment by gturri** [comment]
It has now been completely fixed in the fork https://github.com/gturri/aXMLRPC since we now rely on jISO8601 (http://search.maven.org/#search|ga|1|a%3A%22jISO8601%22) to parse the date, and it is itself Android compatible.

(fix available in `master` for now: it hasn't been pushed to maven central yet)

**Comment by gturri** [comment]
Update: the fix is now available in maven central, in fr.turri.aXMLRPC 1.8.3 (search.maven.org/#search|ga|1|axmlrpc)
