### ISSUE TITLE
publish 1.8.1 to maven central

### ISSUE THREAD

**Issue by micgro42** [timroes/aXMLRPC#48]
Hi,

I would greatly appreciate it if you could publish version 1.8.1 to maven central so that other projects on maven central can depend on it.

Cheers and thank you for providing this great piece of software.

**Comment by timroes** [comment]
Maven Central has way higher standards/rules/requirements than JCenter. The gradle build script I wrote currently doesn't generate enough to publish on maven central (e.g. generate signatures).

I understand the need for some projects to have it on maven central, but unfortunately currently don't have the time to fix all this, so I wouldn't expect any release on Maven Central. If this is something important to you, you could also pull your dependencies from jcenter instead of maven central (everything in maven central is also in jcenter automatically) and just pull in version 1.8.1 of aXMLRPC manually (so it won't try to resolve to 1.8.0 as linked in dokuJClient).

**Comment by gturri** [comment]
Hi @timroes ,

Since I'm not familiar with Gradle, I may be saying something dumb; but before 7fd68d234771b765e0e6db6c853681b221d23c91 it was possible to publish on maven central, so isn't it possible to partially revert this commit in order to be able to manually push both to maven central and to jcenter?
(More precisely, wouldn't  adding back the deleted lines allow this?)

Of course, with this approach it wouldn't be possible to let jcenter sync to maven central, so both push would need to be manual, but since the frequency of the releases if rather low, I guess it shouldn't be an issue.

What do you think?

NB: "you could also pull your dependencies from jcenter instead of maven central"
Actually the issue isn't really about using axmlrpc, but rather redistributing projects which are using it

**Comment by gturri** [comment]
In case someone else finds this issue: if you need axmlrpc 1.8.1 from maven central, you may use fr.turri.aXMLRPC 1.8.2. The code is exactly the same as 1.8.1. I just forked to change the group Id  in order to get the permissions to publish it.
