### ISSUE TITLE
Search for a new maintainer

### ISSUE THREAD

**Issue by timroes** [timroes/aXMLRPC#49]
Since I haven't consumed any XML-RPC interface in around 2-3 years now (since luckily REST and JSON are now a widely accepted standard), I am not in use of this library anymore. That way I am also not contributing any time into it anymore. I started developing in version 2, which would have been a completely rewrite from scratch of this library using more modern dependencies, like OkHTTP for network traffic, plans for more extension points (like own de/serializers, custom pre/postprocessors), but due me not needing this library any longer I haven't come far with the implementation.

If you are still consuming XML-RPC interfaces and you are using this library and want to develop or maintain it further: I would be glad to find a new maintainer to who I can transfer this project and who can do whatever he/she likes with it. Also I would recommend changing the package name to be able to publish it on maven central (where you need to have write access to the de.timroes group).

If you feel like maintaining the library especially if you see that you will need it for some more years, just leave me a message here or contact me in person (www.timroes.de).

**Comment by gturri** [comment]
Since I'm using your library, I'm ok to take on this role.

To be honest, I currently only plan to
* fix #47 and #48
* look into future incoming reviews and create new releases accordingly

To put it in a nutshell, if someone else is willing to be a better maintainer, I'll gladly let her take on this role. Otherwise I'll go on within the next few weeks

**Comment by gturri** [comment]
Actually I went ahead and published a fork fr.turri.aXMLRPC 1.8.2 (http://search.maven.org/#artifactdetails|fr.turri|aXMLRPC|1.8.2|jar) (same code as 1.8.1; only differences are the groupId, and that it's available on maven central instead of JCenter)

That being said, let's keep this issue open a bit more, because if a someone else is also interested in maintaing aXMLRPC, I would gladly let this role.

**Comment by timroes** [comment]
@gturri I would like to transfer you this original repo, which will cause all git clones of this repo (and forks) forward to your repo. Therefor you would need to delete your repository, because it only works as long as you don't already have a repository with that name. I just merged all your changes via a pull request into this repository. Could you please delete yours, so I will be able to transfer you this repository?

**Comment by gturri** [comment]
It would indeed be more clear for users, to know where they should open bug reports.
I just deleted my fork.

One question though: isn't it likely to invalidate the url https://github.com/timroes/aXMLRPC? Wouldn't it be a shame to break all the links pointing at it?

**Comment by timroes** [comment]
The web traffic should be redirected as well according to their documentation: https://help.github.com/articles/transferring-a-repository/#redirects-and-git-remotes

But we'll see in a moment :-)

**Comment by timroes** [comment]
Thanks for accepting. Forwarding works perfectly fine!
